from ubuntu:16.04

CMD ["/bin/sh", "-c", "echo 'Hello from the ssh-able container. \nWe will be running tail -f /dev/null' && tail -f /dev/null"]
#ENTRYPOINT ["/bin/echo", "Hello from the ssh-able container; we'll run 'tail -f /dev/null'; "]
